// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFGQCjBvRfpg_7-hDbYyKA108vY6-hQc0',
    appId: '1:337599404062:web:9f05a460ffff98be73760f',
    messagingSenderId: '337599404062',
    projectId: 'emart-8d623',
    authDomain: 'emart-8d623.firebaseapp.com',
    storageBucket: 'emart-8d623.appspot.com',
    measurementId: 'G-Z90ZY499B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs_yw3e2EP24awtM9nYJ1Gq4guRxCr39k',
    appId: '1:337599404062:android:64609daa6e3e41cb73760f',
    messagingSenderId: '337599404062',
    projectId: 'emart-8d623',
    storageBucket: 'emart-8d623.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyExfnD3-lj27TQCK0xrxoD97ya_DyN0o',
    appId: '1:337599404062:ios:76fa13064c06568273760f',
    messagingSenderId: '337599404062',
    projectId: 'emart-8d623',
    storageBucket: 'emart-8d623.appspot.com',
    iosBundleId: 'com.example.emartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyExfnD3-lj27TQCK0xrxoD97ya_DyN0o',
    appId: '1:337599404062:ios:76fa13064c06568273760f',
    messagingSenderId: '337599404062',
    projectId: 'emart-8d623',
    storageBucket: 'emart-8d623.appspot.com',
    iosBundleId: 'com.example.emartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFGQCjBvRfpg_7-hDbYyKA108vY6-hQc0',
    appId: '1:337599404062:web:e427fcd2b049dc7c73760f',
    messagingSenderId: '337599404062',
    projectId: 'emart-8d623',
    authDomain: 'emart-8d623.firebaseapp.com',
    storageBucket: 'emart-8d623.appspot.com',
    measurementId: 'G-TEXBR9YX6R',
  );
}
